#!/usr/bin/env python3
"""yana-ai design — design context extraction and DESIGN.md generation.

Inspired by bergside/design-md-chrome. Extracts design tokens from URLs or
local CSS/HTML files and generates a DESIGN.md for use as AI agent context.

Subcommands:
  extract <url|file>  Extract design tokens (colors, fonts, spacing, shadows)
  show   [target]     Show current design context from .yana-ai/design/
  init   [target]     Generate DESIGN.md from extracted tokens
  diff   <url1> <url2> Compare two design systems
"""

import argparse, json, os, re, sys
from pathlib import Path
from datetime import datetime, timezone
from urllib.request import urlopen, Request
from urllib.error import URLError

REPO_ROOT   = Path(__file__).parent.parent.parent
DESIGN_DIR  = ".yana-ai/design"
DESIGN_FILE = "design-context.json"
DESIGN_MD   = "DESIGN.md"

BOLD="\033[1m"; GREEN="\033[32m"; RED="\033[31m"; YELLOW="\033[33m"
CYAN="\033[36m"; DIM="\033[2m"; MAGENTA="\033[35m"; RESET="\033[0m"

def no_color(): return os.environ.get("YANA_NO_COLOR") or not sys.stdout.isatty()
def c(code,t):  return t if no_color() else f"{code}{t}{RESET}"

# ── Extractors ─────────────────────────────────────────────────────────────────

_HEX_RE    = re.compile(r'#([0-9a-fA-F]{3,8})\b')
_RGB_RE    = re.compile(r'rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+(?:\s*,\s*[\d.]+)?\s*\)')
_HSL_RE    = re.compile(r'hsla?\([^)]+\)')
_VAR_RE    = re.compile(r'--([a-z][\w-]+)\s*:\s*([^;}{]+);')
_FONT_RE   = re.compile(r"font-family\s*:\s*([^;}{]+);")
_FSIZE_RE  = re.compile(r"font-size\s*:\s*([\d.]+(?:px|rem|em|vw|%))")
_SHADOW_RE = re.compile(r"box-shadow\s*:\s*([^;}{]+);")
_RADIUS_RE = re.compile(r"border-radius\s*:\s*([\d.]+(?:px|rem|em|%))")
_SPACE_RE  = re.compile(r"(?:margin|padding)\s*:\s*([\d.]+(?:px|rem|em)(?:\s+[\d.]+(?:px|rem|em))*)")
_TITLE_RE  = re.compile(r'<title[^>]*>([^<]+)</title>', re.I)


def fetch_html(source: str) -> str:
    """Fetch HTML from URL or read from file."""
    if source.startswith("http://") or source.startswith("https://"):
        req = Request(source, headers={"User-Agent": "yana-ai-design/1.0"})
        try:
            with urlopen(req, timeout=15) as r:
                return r.read().decode(errors="replace")
        except URLError as e:
            raise ValueError(f"Could not fetch {source}: {e}")
    else:
        return Path(source).read_text(errors="replace")


def extract_css_from_html(html: str) -> str:
    """Extract inline <style> blocks and referenced CSS content from HTML."""
    styles = re.findall(r'<style[^>]*>(.*?)</style>', html, re.S | re.I)
    return "\n".join(styles)


def extract_tokens(css: str, html: str = "") -> dict:
    """Extract design tokens from CSS content."""
    tokens: dict = {
        "css_variables": {},
        "colors": [],
        "fonts": [],
        "font_sizes": [],
        "shadows": [],
        "border_radii": [],
        "spacing": [],
        "page_title": "",
    }

    # Page title
    m = _TITLE_RE.search(html)
    if m:
        tokens["page_title"] = m.group(1).strip()

    # CSS custom properties (design tokens)
    for key, val in _VAR_RE.findall(css):
        tokens["css_variables"][f"--{key}"] = val.strip()

    # Colors
    colors = set()
    colors.update(_HEX_RE.findall(css))
    colors.update(_RGB_RE.findall(css))
    colors.update(_HSL_RE.findall(css))
    tokens["colors"] = sorted(
        [f"#{c}" if not c.startswith("rgb") and not c.startswith("hsl") else c
         for c in colors]
    )[:40]

    # Fonts
    seen_fonts = set()
    for ff in _FONT_RE.findall(css):
        clean = ff.strip().strip('"').strip("'").split(",")[0].strip().strip('"').strip("'")
        if clean and clean not in seen_fonts and len(clean) < 50:
            seen_fonts.add(clean)
            tokens["fonts"].append(clean)
    tokens["fonts"] = tokens["fonts"][:10]

    # Font sizes
    sizes = sorted(set(_FSIZE_RE.findall(css)))
    tokens["font_sizes"] = sizes[:12]

    # Shadows
    tokens["shadows"] = list(dict.fromkeys(_SHADOW_RE.findall(css)))[:6]

    # Border radii
    tokens["border_radii"] = sorted(set(_RADIUS_RE.findall(css)))[:8]

    # Spacing
    tokens["spacing"] = list(dict.fromkeys(_SPACE_RE.findall(css)))[:8]

    return tokens


def tokens_to_markdown(tokens: dict, source: str) -> str:
    lines = [
        f"# DESIGN.md — {tokens.get('page_title') or source}",
        "",
        f"> Generated by `yana-ai design` from: {source}",
        f"> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "---",
        "",
    ]

    # CSS Variables (design tokens)
    css_vars = tokens.get("css_variables", {})
    if css_vars:
        lines += ["## CSS Custom Properties (Design Tokens)", ""]
        lines += ["```css", ":root {"]
        for k, v in list(css_vars.items())[:30]:
            lines.append(f"  {k}: {v};")
        lines += ["}", "```", ""]

    # Colors
    colors = tokens.get("colors", [])
    if colors:
        lines += ["## Color Palette", ""]
        for col in colors[:20]:
            lines.append(f"- `{col}`")
        lines.append("")

    # Typography
    fonts = tokens.get("fonts", [])
    sizes = tokens.get("font_sizes", [])
    if fonts or sizes:
        lines += ["## Typography", ""]
        if fonts:
            lines.append("**Font families:**")
            for f in fonts:
                lines.append(f"- `{f}`")
        if sizes:
            lines.append("")
            lines.append("**Font sizes:**")
            lines.append(f"`{'` · `'.join(sizes)}`")
        lines.append("")

    # Spacing
    spacing = tokens.get("spacing", [])
    if spacing:
        lines += ["## Spacing", ""]
        for s in spacing:
            lines.append(f"- `{s}`")
        lines.append("")

    # Shadows
    shadows = tokens.get("shadows", [])
    if shadows:
        lines += ["## Shadows", ""]
        for s in shadows:
            lines.append(f"- `{s.strip()}`")
        lines.append("")

    # Border radius
    radii = tokens.get("border_radii", [])
    if radii:
        lines += ["## Border Radius", ""]
        lines.append(f"`{'` · `'.join(radii)}`")
        lines.append("")

    lines += [
        "---",
        "",
        "## Usage as AI context",
        "",
        "Add this file to your project root so AI agents use these design tokens:",
        "",
        "```bash",
        "# Claude Code reads DESIGN.md automatically when in project",
        "cp .yana-ai/design/DESIGN.md ./DESIGN.md",
        "```",
        "",
        "*Generated with [yana-ai design](https://github.com/yanacuti1121/yana-ai)*",
    ]
    return "\n".join(lines)


# ── Commands ───────────────────────────────────────────────────────────────────

def cmd_extract(source: str, target_dir: str, as_json: bool, quiet: bool) -> None:
    if not quiet:
        print()
        print(c(BOLD, "  yana-ai design extract"))
        print(c(DIM, f"  {source}"))
        print()

    if not quiet: print(f"  Fetching…", end="", flush=True)
    try:
        html = fetch_html(source)
    except ValueError as e:
        print(c(RED, f"\n  ✗ {e}"), file=sys.stderr); sys.exit(1)
    if not quiet: print(c(GREEN, " done"))

    css = extract_css_from_html(html)
    if not quiet: print(f"  Extracting tokens from {len(css):,} chars CSS…", end="", flush=True)
    tokens = extract_tokens(css, html)
    tokens["source"] = source
    tokens["extracted_at"] = datetime.now(timezone.utc).isoformat()
    if not quiet: print(c(GREEN, " done"))

    # Save
    design_path = Path(target_dir) / DESIGN_DIR
    design_path.mkdir(parents=True, exist_ok=True)
    json_path = design_path / DESIGN_FILE
    json_path.write_text(json.dumps(tokens, indent=2))

    if as_json:
        print(json.dumps(tokens, indent=2))
        return

    if not quiet:
        n_vars   = len(tokens["css_variables"])
        n_colors = len(tokens["colors"])
        n_fonts  = len(tokens["fonts"])
        print()
        print(f"  {c(BOLD,'CSS variables')}  {n_vars}")
        print(f"  {c(BOLD,'Colors')}         {n_colors}")
        print(f"  {c(BOLD,'Fonts')}          {', '.join(tokens['fonts'][:3]) or 'none'}")
        print(f"  {c(BOLD,'Font sizes')}     {', '.join(tokens['font_sizes'][:5]) or 'none'}")
        if tokens["shadows"]:
            print(f"  {c(BOLD,'Shadows')}        {len(tokens['shadows'])}")
        print()
        print(c(GREEN, f"  ✓ Saved: {json_path}"))
        print(c(DIM,   f"  Run: yana-ai design init   — to generate DESIGN.md"))
        print()


def cmd_show(target_dir: str, as_json: bool) -> None:
    json_path = Path(target_dir) / DESIGN_DIR / DESIGN_FILE
    if not json_path.exists():
        print(c(RED, f"  ✗ No design context. Run: yana-ai design extract <url>"), file=sys.stderr)
        sys.exit(1)
    tokens = json.loads(json_path.read_text())
    if as_json:
        print(json.dumps(tokens, indent=2))
        return
    print()
    print(c(BOLD, f"  Design context — {tokens.get('page_title') or tokens.get('source','')}"))
    print(c(DIM,  f"  {tokens.get('source','')} · {tokens.get('extracted_at','')[:10]}"))
    print()
    for k in ("css_variables","colors","fonts","font_sizes","border_radii","shadows","spacing"):
        val = tokens.get(k)
        if not val: continue
        if isinstance(val, dict):
            print(f"  {c(BOLD,k)} ({len(val)})")
            for kk,vv in list(val.items())[:5]:
                print(f"    {c(CYAN,kk)}: {vv}")
            if len(val) > 5: print(c(DIM, f"    … {len(val)-5} more"))
        elif isinstance(val, list):
            print(f"  {c(BOLD,k)}: {', '.join(str(v) for v in val[:6])}")
        print()


def cmd_init(target_dir: str, out_path: str|None) -> None:
    json_path = Path(target_dir) / DESIGN_DIR / DESIGN_FILE
    if not json_path.exists():
        print(c(RED, f"  ✗ No design context. Run: yana-ai design extract <url>"), file=sys.stderr)
        sys.exit(1)
    tokens = json.loads(json_path.read_text())
    md = tokens_to_markdown(tokens, tokens.get("source","unknown"))
    dest = Path(out_path) if out_path else Path(target_dir) / DESIGN_DIR / DESIGN_MD
    dest.write_text(md)
    print(c(GREEN, f"  ✓ DESIGN.md written: {dest}"))
    print(c(DIM,   f"  Copy to project root: cp {dest} ./DESIGN.md"))


def main():
    parser = argparse.ArgumentParser(prog="yana-ai design",
        description="Extract design tokens from any URL → DESIGN.md for AI context")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_ex = sub.add_parser("extract", help="Extract design tokens from URL or file")
    p_ex.add_argument("source", help="URL or HTML file path")
    p_ex.add_argument("--target", default=".", help="Project dir (default: .)")
    p_ex.add_argument("--json",  action="store_true")
    p_ex.add_argument("--quiet", action="store_true")

    p_sh = sub.add_parser("show", help="Show extracted design context")
    p_sh.add_argument("target", nargs="?", default=".")
    p_sh.add_argument("--json", action="store_true")

    p_in = sub.add_parser("init", help="Generate DESIGN.md from extracted tokens")
    p_in.add_argument("target", nargs="?", default=".")
    p_in.add_argument("--out", default=None, help="Output path (default: .yana-ai/design/DESIGN.md)")

    args = parser.parse_args()

    if args.cmd == "extract":
        cmd_extract(args.source, args.target, args.json, args.quiet)
    elif args.cmd == "show":
        cmd_show(args.target, args.json)
    elif args.cmd == "init":
        cmd_init(args.target, args.out)


if __name__ == "__main__":
    main()
