#!/usr/bin/env python3
"""yana-ai export [target] — export findings to CSV/JSON/Markdown."""

import argparse
import csv
import io
import json
import os
import subprocess
import sys
from datetime import datetime

REPO_ROOT  = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCANNER_PY = os.path.join(REPO_ROOT, "core/scripts/audit_scanner.py")

BOLD  = "\033[1m"; GREEN = "\033[32m"; DIM = "\033[2m"; RED = "\033[31m"; RESET = "\033[0m"

def no_color():
    return os.environ.get("YANA_NO_COLOR") or not sys.stdout.isatty()

def c(code, text):
    return text if no_color() else f"{code}{text}{RESET}"


def run_audit(target: str, extra: list[str]) -> dict:
    r = subprocess.run([sys.executable, SCANNER_PY, target, "--json"] + extra,
                       capture_output=True, text=True)
    try:
        return json.loads(r.stdout)
    except Exception:
        print(c(RED, "Error: audit failed"), file=sys.stderr); sys.exit(3)


def to_csv(data: dict) -> str:
    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=["id","severity","file","line","description","fix"])
    writer.writeheader()
    for f in data.get("findings", []):
        writer.writerow({
            "id":          f.get("id",""),
            "severity":    f.get("severity",""),
            "file":        f.get("file",""),
            "line":        f.get("line",""),
            "description": f.get("description",""),
            "fix":         f.get("fix",""),
        })
    return out.getvalue()


def to_markdown(data: dict, target: str) -> str:
    score    = data.get("score", 0)
    risk     = data.get("risk_level", "?")
    findings = data.get("findings", [])
    ts       = datetime.now().strftime("%Y-%m-%d %H:%M")
    scanned  = data.get("files_scanned", 0)

    lines = [
        f"# Yana AI Audit Report",
        f"",
        f"**Target:** `{os.path.abspath(target)}`  ",
        f"**Date:** {ts}  ",
        f"**Score:** {score}/100 · **Risk:** {risk}  ",
        f"**Files scanned:** {scanned}  ",
        f"",
    ]

    if not findings:
        lines += ["## Findings", "", "✓ No findings.", ""]
    else:
        by_sev = {}
        for f in findings:
            s = f.get("severity","LOW")
            by_sev.setdefault(s, []).append(f)

        for sev in ("CRITICAL","HIGH","MED","MEDIUM","LOW"):
            group = by_sev.get(sev, [])
            if not group:
                continue
            lines += [f"## {sev} ({len(group)})", ""]
            lines += ["| ID | File | Description | Fix |",
                      "|---|---|---|---|"]
            for f in group:
                fid  = f.get("id","")
                file = f.get("file","")
                line = f.get("line","")
                desc = f.get("description","").replace("|","\\|")
                fix  = f.get("fix","").replace("|","\\|")
                loc  = f"{file}:{line}" if line else file
                lines.append(f"| `{fid}` | `{loc}` | {desc} | {fix} |")
            lines.append("")

    lines += [
        "---",
        f"*Generated by [Yana AI](https://github.com/yanacuti1121/yana-ai)*",
    ]
    return "\n".join(lines)


def to_junit(data: dict) -> str:
    findings = data.get("findings", [])
    score    = data.get("score", 0)
    failures = len([f for f in findings if f.get("severity") in ("CRITICAL","HIGH")])
    ts       = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<testsuite name="yana-ai-audit" tests="{len(findings)+1}" failures="{failures}" timestamp="{ts}">',
        f'  <testcase name="audit-score" classname="yana-ai">',
    ]
    if score < 70:
        lines.append(f'    <failure message="Score {score}/100 below threshold">Score: {score}/100 Risk: {data.get("risk_level")}</failure>')
    lines.append('  </testcase>')

    for f in findings:
        sev  = f.get("severity","LOW")
        fid  = f.get("id","?")
        desc = f.get("description","")
        file = f.get("file","")
        lines.append(f'  <testcase name="{fid}" classname="{file}">')
        if sev in ("CRITICAL","HIGH"):
            lines.append(f'    <failure message="{desc}">{desc}&#10;Fix: {f.get("fix","")}</failure>')
        lines.append('  </testcase>')

    lines.append('</testsuite>')
    return "\n".join(lines)


FORMATS = {
    "csv":      (to_csv,      "yana-ai-findings.csv"),
    "markdown": (to_markdown, "yana-ai-report.md"),
    "md":       (to_markdown, "yana-ai-report.md"),
    "junit":    (to_junit,    "yana-ai-junit.xml"),
    "json":     (None,        "yana-ai-findings.json"),
}


def main():
    parser = argparse.ArgumentParser(
        prog="yana-ai export",
        description="Export audit findings to CSV/Markdown/JUnit/JSON",
    )
    parser.add_argument("target",  nargs="?", default=".")
    parser.add_argument("--format", choices=list(FORMATS.keys()), default="csv",
                        help="Output format (default: csv)")
    parser.add_argument("--out",   default=None, help="Output file (default: auto)")
    parser.add_argument("--stdout", action="store_true", help="Print to stdout instead of file")
    parser.add_argument("--ignore", metavar="ID", action="append", default=[])
    parser.add_argument("--diff",   default="")
    args = parser.parse_args()

    extra = []
    for ig in args.ignore:
        extra += ["--ignore", ig]
    if args.diff:
        extra += ["--diff", args.diff]

    if not args.stdout:
        print(c(DIM, f"  Scanning {args.target}…"), end="", flush=True)
    data = run_audit(args.target, extra)
    if not args.stdout:
        print(c(GREEN, " done"))

    fmt_fn, default_out = FORMATS[args.format]

    if args.format == "json":
        content = json.dumps(data, indent=2)
    elif args.format in ("markdown", "md"):
        content = fmt_fn(data, args.target)
    else:
        content = fmt_fn(data)

    if args.stdout:
        print(content)
        return

    out_path = args.out or default_out
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    score = data.get("score", 0)
    risk  = data.get("risk_level", "?")
    finds = len(data.get("findings", []))
    print(f"  Score: {score}/100 {risk}  ·  {finds} findings")
    print(c(GREEN, f"  ✓ Exported ({args.format.upper()}): {out_path}"))
    print()


if __name__ == "__main__":
    main()
