#!/usr/bin/env python3
"""
graph_query.py — yana-ai graph subcommands: search, onboard, diff, show

Adapted from Lum1104/Understand-Anything (MIT):
  - context-builder.ts  → search + expand logic
  - onboard-builder.ts  → onboarding guide format
  - diff-analyzer.ts    → diff impact analysis
"""

import argparse
import json
import os
import re
import subprocess
import sys

from graph_builder import (
    GRAPH_DIR, GRAPH_FILE, build_graph, load_graph,
    BOLD, GREEN, RED, CYAN, DIM, YELLOW, RESET, c, no_color,
)

# ── Search ────────────────────────────────────────────────────────────────────

def search_nodes(graph: dict, query: str, limit: int = 15) -> list[dict]:
    """Keyword search across node id, name, summary, tags, file_path."""
    q = query.lower()
    scored = []
    for node in graph["nodes"]:
        score = 0
        if q in node.get("name", "").lower():       score += 3
        if q in node.get("file_path", "").lower():  score += 2
        if q in node.get("summary", "").lower():    score += 2
        if any(q in t for t in node.get("tags", [])): score += 1
        if q in node["id"].lower():                 score += 1
        if score > 0:
            scored.append((score, node))
    scored.sort(key=lambda x: -x[0])
    return [n for _, n in scored[:limit]]


def expand_context(graph: dict, nodes: list[dict]) -> list[dict]:
    """1-hop expand: include neighboring nodes."""
    node_ids = {n["id"] for n in nodes}
    neighbors = []
    for edge in graph["edges"]:
        if edge["type"] in ("imports", "calls", "contains"):
            if edge["source"] in node_ids and edge["target"] not in node_ids:
                target_node = next(
                    (n for n in graph["nodes"] if n["id"] == edge["target"]), None
                )
                if target_node:
                    neighbors.append(target_node)
            elif edge["target"] in node_ids and edge["source"] not in node_ids:
                src_node = next(
                    (n for n in graph["nodes"] if n["id"] == edge["source"]), None
                )
                if src_node:
                    neighbors.append(src_node)
    # Deduplicate
    seen = node_ids.copy()
    unique = []
    for n in neighbors:
        if n["id"] not in seen:
            seen.add(n["id"])
            unique.append(n)
    return nodes + unique[:10]


def cmd_search(graph: dict, query: str, expand: bool = False,
               as_json: bool = False) -> None:
    hits = search_nodes(graph, query)
    if expand:
        hits = expand_context(graph, hits)

    if as_json:
        print(json.dumps({"query": query, "results": hits}, indent=2))
        return

    print()
    print(c(BOLD, f"  Search: {query}"))
    print(c(DIM, f"  {len(hits)} result(s)"))
    print()

    if not hits:
        print(c(YELLOW, "  No matches found."))
        print()
        return

    for node in hits:
        ntype = node.get("type", "?")
        name  = node.get("name", node["id"])
        fpath = node.get("file_path", "")
        sev   = node.get("complexity", "")
        summary = node.get("summary", "")

        type_color = {
            "file": CYAN, "function": GREEN,
            "class": YELLOW, "config": DIM,
        }.get(ntype, "")

        print(f"  {c(type_color, f'[{ntype}]'):<20} {c(BOLD, name)}")
        if fpath and fpath != name:
            print(f"  {'':20} {c(DIM, fpath)}")
        if summary:
            print(f"  {'':20} {summary[:100]}")
    print()

# ── Onboarding guide ──────────────────────────────────────────────────────────

def cmd_onboard(graph: dict, out_file: str | None = None) -> None:
    """Build onboarding guide — adapted from onboard-builder.ts."""
    proj = graph["project"]
    nodes = graph["nodes"]
    layers = graph["layers"]
    tour = graph["tour"]
    edges = graph["edges"]

    lines = []
    lines.append(f"# {proj['name']} — Onboarding Guide\n")
    lines.append(f"> Generated by yana-ai graph onboard\n")
    lines.append(f"> Source: Understand-Anything pipeline (Lum1104/Understand-Anything)\n")
    lines.append("")

    # Project overview table
    lines.append("## Project Overview\n")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    if proj.get("description"):
        lines.append(f"| Description | {proj['description']} |")
    lines.append(f"| Languages | {', '.join(proj.get('languages', [])) or 'n/a'} |")
    if proj.get("frameworks"):
        lines.append(f"| Frameworks | {', '.join(proj['frameworks'])} |")
    lines.append(f"| Total files | {proj.get('total_files', '?')} |")
    lines.append(f"| Analysed | {proj.get('analysis_timestamp', '?')[:10]} |")
    lines.append("")

    # Architecture layers
    lines.append("## Architecture\n")
    for layer in layers:
        member_names = []
        for mid in layer["members"][:5]:
            n = next((nd for nd in nodes if nd["id"] == mid), None)
            if n:
                member_names.append(f"`{n['name']}`")
        if not member_names:
            continue
        lines.append(f"### {layer['name']}")
        lines.append(f"Key members: {', '.join(member_names)}"
                     + (f" and {len(layer['members'])-5} more" if len(layer["members"]) > 5 else ""))
        lines.append("")

    # Getting Started Tour
    lines.append("## Getting Started\n")
    lines.append("Follow this dependency-ordered reading path:\n")
    for step in tour[:15]:
        fpath = step.get("file_path", step["node_id"])
        reason = step.get("reason", "")
        lines.append(f"{step['step']}. **`{fpath}`** — {reason}")
    lines.append("")

    # File map
    lines.append("## File Map\n")
    lines.append("| File | Language | Complexity |")
    lines.append("|------|----------|------------|")
    file_nodes = [n for n in nodes if n["type"] == "file"][:30]
    for n in file_nodes:
        lines.append(f"| `{n['file_path']}` | {n.get('language', '?')} | {n.get('complexity', '?')} |")
    if len([n for n in nodes if n["type"] == "file"]) > 30:
        total = len([n for n in nodes if n["type"] == "file"])
        lines.append(f"| *… and {total - 30} more* | | |")
    lines.append("")

    # Complexity hotspots
    hotspots = [n for n in file_nodes if n.get("complexity") == "high"]
    if hotspots:
        lines.append("## Complexity Hotspots\n")
        lines.append("These files have high complexity and deserve extra attention:\n")
        for n in hotspots[:10]:
            lines.append(f"- **`{n['file_path']}`** ({n.get('language', '?')})")
        lines.append("")

    # Attribution
    lines.append("---")
    lines.append("*Knowledge graph built with [yana-ai](https://github.com/yanacuti1121/yana-ai)*")
    lines.append("*Pipeline adapted from [Understand-Anything](https://github.com/Lum1104/Understand-Anything) (MIT)*")

    guide = "\n".join(lines)

    if out_file:
        with open(out_file, "w") as f:
            f.write(guide)
        print(c(GREEN, f"  ✓ Onboarding guide: {out_file}"))
    else:
        print(guide)


# ── Diff impact analysis ──────────────────────────────────────────────────────

def get_changed_files(base: str, target: str) -> list[str]:
    """Get files changed vs a git base."""
    try:
        r = subprocess.run(
            ["git", "diff", "--name-only", base],
            cwd=target, capture_output=True, text=True, timeout=15,
        )
        return [l.strip() for l in r.stdout.splitlines() if l.strip()]
    except Exception:
        return []


def cmd_diff(graph: dict, changed_files: list[str],
             as_json: bool = False) -> None:
    """Diff impact analysis — adapted from diff-analyzer.ts."""
    nodes = graph["nodes"]
    edges = graph["edges"]

    node_by_path = {n.get("file_path", ""): n for n in nodes if "file_path" in n}

    changed_nodes = []
    unmapped = []
    for f in changed_files:
        n = node_by_path.get(f)
        if n:
            changed_nodes.append(n)
        else:
            unmapped.append(f)

    # Include child nodes (contains edges) of changed nodes
    changed_ids = {n["id"] for n in changed_nodes}
    for edge in edges:
        if edge["type"] == "contains" and edge["source"] in changed_ids:
            child = next((n for n in nodes if n["id"] == edge["target"]), None)
            if child and child["id"] not in changed_ids:
                changed_nodes.append(child)
                changed_ids.add(child["id"])

    # Find 1-hop affected nodes
    affected_nodes = []
    affected_ids = set()
    for edge in edges:
        if edge["type"] in ("imports", "calls"):
            if edge["source"] in changed_ids and edge["target"] not in changed_ids:
                n = next((nd for nd in nodes if nd["id"] == edge["target"]), None)
                if n and n["id"] not in affected_ids:
                    affected_nodes.append(n)
                    affected_ids.add(n["id"])
            elif edge["target"] in changed_ids and edge["source"] not in changed_ids:
                n = next((nd for nd in nodes if nd["id"] == edge["source"]), None)
                if n and n["id"] not in affected_ids:
                    affected_nodes.append(n)
                    affected_ids.add(n["id"])

    all_impacted = changed_ids | affected_ids
    impacted_edges = [e for e in edges
                      if e["source"] in all_impacted or e["target"] in all_impacted]

    affected_layers = [l for l in graph["layers"]
                       if any(m in all_impacted for m in l["members"])]

    # Risk assessment
    risks = []
    high_complexity = [n for n in changed_nodes if n.get("complexity") == "high"]
    if high_complexity:
        risks.append(f"{len(high_complexity)} high-complexity component(s) changed")
    if len(affected_layers) > 1:
        risks.append(f"change spans {len(affected_layers)} architectural layers")
    if len(affected_nodes) >= 5:
        risks.append(f"wide blast radius — {len(affected_nodes)} affected components")
    if unmapped:
        risks.append(f"{len(unmapped)} file(s) not yet in graph (run `yana-ai graph build`)")

    risk_level = "HIGH" if len(risks) >= 2 else ("MEDIUM" if risks else "LOW")

    if as_json:
        print(json.dumps({
            "changed_files": changed_files,
            "changed_nodes": changed_nodes,
            "affected_nodes": affected_nodes,
            "impacted_edges": impacted_edges,
            "affected_layers": [l["name"] for l in affected_layers],
            "unmapped_files": unmapped,
            "risk_level": risk_level,
            "risk_factors": risks,
        }, indent=2))
        return

    risk_color = RED if risk_level == "HIGH" else (YELLOW if risk_level == "MEDIUM" else GREEN)
    print()
    print(c(BOLD, "  yana-ai graph diff"))
    print()
    print(f"  {c(BOLD, 'Risk')}  {c(risk_color, risk_level)}")
    if risks:
        for r in risks:
            print(f"    {c(risk_color, '→')} {r}")
    print()

    if changed_nodes:
        print(c(BOLD, f"  Changed components ({len(changed_nodes)})"))
        for n in changed_nodes[:10]:
            print(f"    {c(CYAN, n.get('file_path', n['name'])):<50} {n.get('complexity','?')}")
    if affected_nodes:
        print()
        print(c(BOLD, f"  Affected components ({len(affected_nodes)})"))
        for n in affected_nodes[:10]:
            print(f"    {c(YELLOW, n.get('file_path', n['name']))}")
        if len(affected_nodes) > 10:
            print(c(DIM, f"    … and {len(affected_nodes)-10} more"))
    if affected_layers:
        print()
        print(c(BOLD, f"  Affected layers"))
        for l in affected_layers:
            print(f"    {l['name']}")
    if unmapped:
        print()
        print(c(BOLD, f"  Unmapped files (not in graph)"))
        for f in unmapped[:5]:
            print(f"    {c(DIM, f)}")
    print()


# ── Show summary ──────────────────────────────────────────────────────────────

def cmd_show(graph: dict) -> None:
    proj  = graph["project"]
    nodes = graph["nodes"]
    edges = graph["edges"]
    layers = graph["layers"]
    tour  = graph["tour"]

    file_n = sum(1 for n in nodes if n["type"] == "file")
    fn_n   = sum(1 for n in nodes if n["type"] == "function")
    cls_n  = sum(1 for n in nodes if n["type"] == "class")

    print()
    print(c(BOLD, f"  {proj['name']}"))
    if proj.get("description"):
        print(f"  {proj['description'][:100]}")
    print()
    print(f"  {c(BOLD,'Languages')}   {', '.join(proj.get('languages', [])) or 'n/a'}")
    if proj.get("frameworks"):
        print(f"  {c(BOLD,'Frameworks')}  {', '.join(proj['frameworks'])}")
    print(f"  {c(BOLD,'Files')}       {file_n}")
    print(f"  {c(BOLD,'Functions')}   {fn_n}")
    print(f"  {c(BOLD,'Classes')}     {cls_n}")
    print(f"  {c(BOLD,'Edges')}       {len(edges)}")
    print(f"  {c(BOLD,'Analysed')}    {proj.get('analysis_timestamp','?')[:19]}")
    print()
    print(c(BOLD, "  Architecture"))
    for layer in layers:
        print(f"    {layer['name']:<20} {len(layer['members'])} nodes")
    print()
    if tour:
        print(c(BOLD, f"  Tour ({len(tour)} steps)"))
        for step in tour[:5]:
            print(f"    {step['step']:2}. {step.get('file_path', step['node_id'])}")
        if len(tour) > 5:
            print(c(DIM, f"    … and {len(tour)-5} more (run `yana-ai graph onboard`)"))
    print()


# ── CLI entry point ───────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="yana-ai graph",
        description="Knowledge graph commands (Understand-Anything pipeline)",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    # build
    p_build = sub.add_parser("build", help="Build knowledge graph for target")
    p_build.add_argument("target", nargs="?", default=".")
    p_build.add_argument("--quiet", action="store_true")
    p_build.add_argument("--json", action="store_true")

    # show
    p_show = sub.add_parser("show", help="Show graph summary")
    p_show.add_argument("target", nargs="?", default=".")

    # search
    p_search = sub.add_parser("search", help="Search graph nodes")
    p_search.add_argument("query", help="Search query")
    p_search.add_argument("target", nargs="?", default=".")
    p_search.add_argument("--expand", action="store_true",
                           help="Include 1-hop neighbours")
    p_search.add_argument("--json", action="store_true")

    # onboard
    p_onboard = sub.add_parser("onboard", help="Generate onboarding guide (Markdown)")
    p_onboard.add_argument("target", nargs="?", default=".")
    p_onboard.add_argument("--out", metavar="FILE", default=None,
                            help="Write to file instead of stdout")

    # diff
    p_diff = sub.add_parser("diff", help="Diff impact analysis")
    p_diff.add_argument("base", nargs="?", default="HEAD~1",
                         help="Git base to compare against (default: HEAD~1)")
    p_diff.add_argument("target", nargs="?", default=".")
    p_diff.add_argument("--files", metavar="F", nargs="+",
                         help="Explicit list of changed files (skips git diff)")
    p_diff.add_argument("--json", action="store_true")

    args = parser.parse_args()

    if args.cmd == "build":
        graph = build_graph(args.target, quiet=args.quiet)
        if args.json:
            print(json.dumps({"nodes": len(graph["nodes"]),
                               "edges": len(graph["edges"])}, indent=2))
        return

    # All other commands need an existing graph
    target = getattr(args, "target", ".")
    graph = load_graph(target)
    if graph is None:
        print(c(RED, f"  ✗ No graph found. Run: yana-ai graph build {target}"),
              file=sys.stderr)
        sys.exit(1)

    if args.cmd == "show":
        cmd_show(graph)

    elif args.cmd == "search":
        cmd_search(graph, args.query, expand=args.expand,
                   as_json=getattr(args, "json", False))

    elif args.cmd == "onboard":
        cmd_onboard(graph, out_file=args.out)

    elif args.cmd == "diff":
        if args.files:
            changed = args.files
        else:
            changed = get_changed_files(args.base, target)
            if not changed:
                print(c(YELLOW, f"  No changed files vs {args.base}."))
                return
        cmd_diff(graph, changed, as_json=getattr(args, "json", False))


if __name__ == "__main__":
    main()
